Catapult: Include missing okhttp3 library to static_libs
It seems like A14 need an extra line, otherwise it will crash like
this

FATAL EXCEPTION: main
Process: org.lineageos.tv.launcher, PID: 5460
java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/Headers$Builder;
	at coil.util.-Utils.<clinit>(Utils.kt:151)
	at coil.request.DefaultRequestOptions.<init>(DefaultRequestOptions.kt:25)
	at coil.util.-Requests.<clinit>(Requests.kt:15)
	at coil.ImageLoader$Builder.<init>(ImageLoader.kt:126)
	at coil.ImageLoaders.create(ImageLoaders.kt:16)
	at coil.Coil.newImageLoader(Coil.kt:75)
	at coil.Coil.imageLoader(Coil.kt:27)
	at org.lineageos.tv.launcher.view.WatchNextCard.setInfo(WatchNextCard.kt:24)
	at org.lineageos.tv.launcher.adapter.WatchNextAdapter$ViewHolder.bind(WatchNextAdapter.kt:41)
	at org.lineageos.tv.launcher.adapter.WatchNextAdapter.onBindViewHolder(WatchNextAdapter.kt:28)
	at org.lineageos.tv.launcher.adapter.WatchNextAdapter.onBindViewHolder(WatchNextAdapter.kt:16)

Signed-off-by: hmtheboy154 <buingoc67@gmail.com>